# Generated by Django 3.1.3 on 2020-12-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookRest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
                ('auth_name', models.CharField(max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
